name: CD to github.io
# on:
#   push:
#     branches:
#       - main
on:
  pull_request:
    branches:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache node modules
      # See https://docs.github.com/ja/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install --pure-lockfile
    - run: yarn build
      env:
        CI: false
    - name: Setup git
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        touch ~/.ssh/id_rsa
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: deploy
      run: |
        cd ../
        git clone git@github.com:YunosukeY/YunosukeY.github.io.git
        cd YunosukeY.github.io
        rm -rf static
        cp -r ../poluta-db/build/ .
        git add -A
        git push origin master
